# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3b865f554298da98a5ec192627ed76501c4123e79a354c8946bd6d31893bd429db1ae45302fc238313b96547a41e64652fe5a626725e27dcc9a6f5fb547ed108

test:
  secret_key_base: 25fa33cf418c709b6bc4af51131f1de361e52be9f26d5f490bb3f0b52f189405791889f22e532d42c31f317d103b716e750e2ffeac0c1fcaac99635ff7674b6d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
